version: "3.1"

networks:
  main_network:
    name: main_network

services:
  create_service:
    container_name: create_service_container
    build:
      context: ./create-service
    restart: "no"
    env_file:
      - ./container_files/env-vars/.service.env
    networks:
      - main_network
    command:
      - sh
      - run-prod.sh

  api_gateway:
    container_name: api_gateway_container
    build:
      context: ./api-gateway
    ports:
      - "8000:8000"
    restart: "no"
    env_file:
      - ./container_files/env-vars/.api-gateway.env
    networks:
      - main_network
    command:
      - sh
      - run-prod.sh
